name: jupyterlab_env
channels:
  - conda-forge
dependencies:
  - pydantic-settings
  - python=3.12.4
  - nodejs=20
  - jupyterlab
  - pip
  - pip:
      - nornir
      - pyats
      - genie
      - meraki
      # - jupyter-ai==2.18.1
